services:
  web:
    build:
      target: gpp-hyrax-dev
    volumes:
      - .:/app/doris/gpp-hyrax
      - ./public:/app/doris/gpp-hyrax/public
      - bundle:/bundle

  solr:
    command: >
      sh -c "
      precreate-core hydra-development /opt/solr/server/configsets/hyraxconf;
      solr-precreate hydra-test /opt/solr/server/configsets/hyraxconf;
      "

  sidekiq:
    volumes:
      - .:/app/doris/gpp-hyrax
      - ./public:/app/doris/gpp-hyrax/public
      - bundle:/bundle

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - gpp-hyrax

  chrome:
    image: selenium/standalone-chrome:3.141
    logging:
      driver: none
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2G
    ports:
      - "4444:4444"
      - "5959:5900"
    networks:
      - gpp-hyrax

volumes:
  bundle: