services:
  web:
    image: doris/gpp-hyrax
    build:
      context: .
      target: gpp-hyrax
    command: start-app.sh
    stdin_open: true
    tty: true
    user: root
    env_file: &env_file
      - docker/.env
    depends_on:
      - fcrepo
      - fcrepodb
      - postgres
      - redis
      - solr
    ports:
      - "5000:5000"
    volumes:
      - hyrax-uploads:/data/uploads
      - hyrax-derivatives:/data/derivatives
      - hyrax-imports:/data/imports
      - rails-public:/app/doris/gpp-hyrax/public
      - rails-tmp:/app/doris/gpp-hyrax/tmp:cached
    networks:
      - gpp-hyrax

  sidekiq:
    image: doris/gpp-hyrax
    command: start-sidekiq.sh web:$PORT
    user: root
    env_file: *env_file
    depends_on:
      - web
      - fcrepo
      - fcrepodb
      - postgres
      - redis
      - solr
    volumes:
      - hyrax-uploads:/data/uploads
      - hyrax-derivatives:/data/derivatives
      - hyrax-imports:/data/imports
      - rails-public:/app/doris/gpp-hyrax/public
      - rails-tmp:/app/doris/gpp-hyrax/tmp:cached
    networks:
      - gpp-hyrax

  postgres: &db
    image: postgres:13
    env_file: *env_file
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432
    networks:
      - gpp-hyrax

  fcrepodb:
    <<: *db
    environment:
      - POSTGRES_DB=${FCREPO_DB}
      - POSTGRES_USER=${FCREPO_DB_USER}
      - POSTGRES_PASSWORD=${FCREPO_DB_PASSWORD}
    volumes:
      - db-fcrepo:/var/lib/postgresql/data

  fcrepo:
    image: samvera/fcrepo4:4.7.5
    env_file: *env_file
    depends_on:
      - fcrepodb
    ports:
      - "8984:8080"
    volumes:
      - fcrepo:/data
    environment:
      MODESHAPE_CONFIG: "classpath:/config/jdbc-postgresql/repository.json"
      JAVA_OPTIONS: >-
        -Dfcrepo.postgresql.username=${FCREPO_DB_USER}
        -Dfcrepo.postgresql.password=${FCREPO_DB_PASSWORD}
        -Dfcrepo.postgresql.host=fcrepodb 
        -Dfcrepo.postgresql.port=${DATABASE_PORT}
    networks:
      - gpp-hyrax

  redis:
    image: redis:6
    env_file: *env_file
    volumes:
      - redis:/data
    networks:
      - gpp-hyrax

  solr:
    image: solr:8.11.1
    env_file: *env_file
    ports:
      - "8983:8983"
    command: >
      sh -c "solr-precreate hyrax /opt/solr/server/configsets/hyraxconf;"
    volumes:
      - solr:/var/solr/data:cached
      - ./solr/config:/opt/solr/server/configsets/hyraxconf
    networks:
      - gpp-hyrax

volumes:
  db:
  db-fcrepo:
  fcrepo:
  hyrax-derivatives:
  hyrax-uploads:
  hyrax-imports:
  rails-public:
  rails-tmp:
  redis:
  solr:

networks:
  gpp-hyrax:
    driver: bridge
    name: gpp-hyrax
    driver_opts:
      com.docker.network.bridge.name: br-gpp-hyrax
