terms:
  - id: Actuary, NYC Office of the (NYCOA)
    term: Actuary, NYC Office of the (NYCOA)
  - id: Administrative Justice Coordinator, NYC Office of (AJC)
    term: Administrative Justice Coordinator, NYC Office of (AJC)
  - id: Administrative Trials and Hearings, Office of (OATH)
    term: Administrative Trials and Hearings, Office of (OATH)
  - id: Aging, Department for the (DFTA)
    term: Aging, Department for the (DFTA)
  - id: Animal Welfare, Mayor's Office of (MOAW)
    term: Animal Welfare, Mayor's Office of (MOAW)
  - id: Borough Presidents
    term: Borough Presidents
  - id: Buildings, Department of (DOB)
    term: Buildings, Department of (DOB)
  - id: Business Integrity Commission (BIC)
    term: Business Integrity Commission (BIC)
  - id: Campaign Finance Board (CFB)
    term: Campaign Finance Board (CFB)
  - id: Center for Innovation through Data Intelligence (CIDI)
    term: Center for Innovation through Data Intelligence (CIDI)
  - id: Chief Medical Examiner, NYC Office of (OCME)
    term: Chief Medical Examiner, NYC Office of (OCME)
  - id: Children's Services, Administration for (ACS)
    term: Children's Services, Administration for (ACS)
  - id: City Clerk, Office of the (CLERK)
    term: City Clerk, Office of the (CLERK)
  - id: City Council, New York (NYCC)
    term: City Council, New York (NYCC)
  - id: City Planning, Department of (DCP)
    term: City Planning, Department of (DCP)
  - id: Citywide Administrative Services, Department of (DCAS)
    term: Citywide Administrative Services, Department of (DCAS)
  - id: Civic Engagement Commision (CEC)
    term: Civic Engagement Commision (CEC)
  - id: Civil Service Commission (CSC)
    term: Civil Service Commission (CSC)
  - id: Civilian Complaint Review Board (CCRB)
    term: Civilian Complaint Review Board (CCRB)
  - id: Commission on Gender Equity (CGE)
    term: Commission on Gender Equity (CGE)
  - id: Commission to Combat Police Corruption (CCPC)
    term: Commission to Combat Police Corruption (CCPC)
  - id: Community Affairs Unit (CAU)
    term: Community Affairs Unit (CAU)
  - id: Community Boards
    term: Community Boards
  - id: Comptroller (COMP)
    term: Comptroller (COMP)
  - id: Conflicts of Interest Board (COIB)
    term: Conflicts of Interest Board (COIB)
  - id: Consumer and Worker Protection, Department of (DCWP)
    term: Consumer and Worker Protection, Department of (DCWP)
  - id: Contract Services, Mayor's Office of (MOCS)
    term: Contract Services, Mayor's Office of (MOCS)
  - id: Correction, Board of (BOC)
    term: Correction, Board of (BOC)
  - id: Correction, Department of (DOC)
    term: Correction, Department of (DOC)
  - id: Criminal Justice, Mayor's Office of (MOCJ)
    term: Criminal Justice, Mayor's Office of (MOCJ)
  - id: Cultural Affairs, Department of (DCLA)
    term: Cultural Affairs, Department of (DCLA)
  - id: Data Analytics, Mayor's Office of (MODA)
    term: Data Analytics, Mayor's Office of (MODA)
  - id: Design and Construction, Department of (DDC)
    term: Design and Construction, Department of (DDC)
  - id: Districting Commission
    term: Districting Commission
  - id: Economic Development Corporation (EDC)
    term: Economic Development Corporation (EDC)
  - id: Economic Opportunity, Mayor's Office for (Opportunity)
    term: Economic Opportunity, Mayor's Office for (Opportunity)
  - id: Education, Department of (DOE)
    term: Education, Department of (DOE)
  - id: Elections, Board of (BOE)
    term: Elections, Board of (BOE)
  - id: Emergency Management, Office of (OEM)
    term: Emergency Management, Office of (OEM)
  - id: End Domestic and Gender-Based Violence, Mayor's Office to (ENDGBV)
    term: End Domestic and Gender-Based Violence, Mayor's Office to (ENDGBV)
  - id: Environmental Coordination, Mayor's Office of (OEC)
    term: Environmental Coordination, Mayor's Office of (OEC)
  - id: Environmental Protection, Department of (DEP)
    term: Environmental Protection, Department of (DEP)
  - id: Environmental Remediation, Mayor's Office of (OER)
    term: Environmental Remediation, Mayor's Office of (OER)
  - id: Equal Employment Practices Commission (EEPC)
    term: Equal Employment Practices Commission (EEPC)
  - id: Finance, Department of (DOF)
    term: Finance, Department of (DOF)
  - id: Financial Information Services Agency - Office of Payroll Administration (FISA-OPA)
    term: Financial Information Services Agency - Office of Payroll Administration (FISA-OPA)
  - id: Fire Department, New York City (FDNY)
    term: Fire Department, New York City (FDNY)
  - id: Food Policy Director, Mayor's Office of the (MOFP)
    term: Food Policy Director, Mayor's Office of the (MOFP)
  - id: GreeNYC (GNYC)
    term: GreeNYC (GNYC)
  - id: Health and Hospitals Corporation (HHC)
    term: Health and Hospitals Corporation (HHC)
  - id: Health and Mental Hygiene, Department of (DOHMH)
    term: Health and Mental Hygiene, Department of (DOHMH)
  - id: Homeless Services, Department of (DHS)
    term: Homeless Services, Department of (DHS)
  - id: Housing Authority, New York City (NYCHA)
    term: Housing Authority, New York City (NYCHA)
  - id: Housing Preservation and Development, Department of (HPD)
    term: Housing Preservation and Development, Department of (HPD)
  - id: Housing Recovery Operations (HRO)
    term: Housing Recovery Operations (HRO)
  - id: Human Resources Administration (HRA)
    term: Human Resources Administration (HRA)
  - id: Human Rights, City Commission on (CCHR)
    term: Human Rights, City Commission on (CCHR)
  - id: Immigrant Affairs, Mayor's Office of (MOIA)
    term: Immigrant Affairs, Mayor's Office of (MOIA)
  - id: Independent Budget Office, NYC (IBO)
    term: Independent Budget Office, NYC (IBO)
  - id: Information Privacy, Mayor's Office of (MOIP)
    term: Information Privacy, Mayor's Office of (MOIP)
  - id: Information Technology and Telecommunications, Department of (DOITT)
    term: Information Technology and Telecommunications, Department of (DOITT)
  - id: Inspector General NYPD, Office of the (OIG-NYPD)
    term: Inspector General NYPD, Office of the (OIG-NYPD)
  - id: Intergovernmental Affairs, Mayor's Office of (MOIGA)
    term: Intergovernmental Affairs, Mayor's Office of (MOIGA)
  - id: International Affairs, Mayor's Office for (IA)
    term: International Affairs, Mayor's Office for (IA)
  - id: Investigation, Department of (DOI)
    term: Investigation, Department of (DOI)
  - id: Labor Relations, NYC Office of (OLR)
    term: Labor Relations, NYC Office of (OLR)
  - id: Landmarks Preservation Commission (LPC)
    term: Landmarks Preservation Commission (LPC)
  - id: Law Department (LAW)
    term: Law Department (LAW)
  - id: Loft Board (LOFT)
    term: Loft Board (LOFT)
  - id: Long-Term Planning &amp; Sustainability, Office of (OLTPS)
    term: Long-Term Planning &amp; Sustainability, Office of (OLTPS)
  - id: Management and Budget, Office of (OMB)
    term: Management and Budget, Office of (OMB)
  - id: Mayor's Fund to Advance NYC (FUND)
    term: Mayor's Fund to Advance NYC (FUND)
  - id: Mayor's Office (OM)
    term: Mayor's Office (OM)
  - id: Media and Entertainment, Mayor's Office of (MOME)
    term: Media and Entertainment, Mayor's Office of (MOME)
  - id: Municipal Drug Strategy Council (MDSC)
    term: Municipal Drug Strategy Council (MDSC)
  - id: New Business Acceleration Team (NBAT)
    term: New Business Acceleration Team (NBAT)
  - id: New York City Fire Pension Fund
    term: New York City Fire Pension Fund
  - id: NYC & Company (NYCGO)
    term: NYC & Company (NYCGO)
  - id: NYC Employees' Retirement System (NYCERS)
    term: NYC Employees' Retirement System (NYCERS)
  - id: NYC Service (SERVICE)
    term: NYC Service (SERVICE)
  - id: Operations, Mayor's Office of (OPS)
    term: Operations, Mayor's Office of (OPS)
  - id: Parks and Recreation, Department of (DPR)
    term: Parks and Recreation, Department of (DPR)
  - id: People with Disabilities, Mayor's Office of (MOPD)
    term: People with Disabilities, Mayor's Office of (MOPD)
  - id: Police Department (NYPD)
    term: Police Department (NYPD)
  - id: Police Pension Fund (PPF)
    term: Police Pension Fund (PPF)
  - id: Probation, Department of (DOP)
    term: Probation, Department of (DOP)
  - id: Procurement Policy Board (PPB)
    term: Procurement Policy Board (PPB)
  - id: Protect Tenants, Mayor's Office to (MOPT)
    term: Protect Tenants, Mayor's Office to (MOPT)
  - id: Public Administrator, Bronx County (PABX)
    term: Public Administrator, Bronx County (PABX)
  - id: Public Administrator, Kings County (PAKC)
    term: Public Administrator, Kings County (PAKC)
  - id: Public Administrator, New York County (PABX)
    term: Public Administrator, New York County (PABX)
  - id: Public Administrator, Queens County (PAQC)
    term: Public Administrator, Queens County (PAQC)
  - id: Public Administrator, Richmond County (PARC)
    term: Public Administrator, Richmond County (PARC)
  - id: Public Advocate (PUB ADV)
    term: Public Advocate (PUB ADV)
  - id: Public Design Commission (DesignCommission)
    term: Public Design Commission (DesignCommission)
  - id: Quadrennial Advisory Commission (QuadAC)
    term: Quadrennial Advisory Commission (QuadAC)
  - id: Records and Information Services, Department of (DORIS)
    term: Records and Information Services, Department of (DORIS)
  - id: Recovery & Resiliency, Mayor's Office of (ORR)
    term: Recovery & Resiliency, Mayor's Office of (ORR)
  - id: Rent Guidelines Board (RGB)
    term: Rent Guidelines Board (RGB)
  - id: Sanitation, Department of (DSNY)
    term: Sanitation, Department of (DSNY)
  - id: School Construction Authority (SCA)
    term: School Construction Authority (SCA)
  - id: Small Business Services, Department of (SBS)
    term: Small Business Services, Department of (SBS)
  - id: Standards and Appeals, Board of (BSA)
    term: Standards and Appeals, Board of (BSA)
  - id: Sustainability, Mayor's Office of (Sustainability)
    term: Sustainability, Mayor's Office of (Sustainability)
  - id: Tax Appeals Tribunal, New York City (TAT)
    term: Tax Appeals Tribunal, New York City (TAT)
  - id: Tax Commission, New York City (TC)
    term: Tax Commission, New York City (TC)
  - id: Taxi and Limousine Commission (TLC)
    term: Taxi and Limousine Commission (TLC)
  - id: Technology and Innovation, Mayor's Office of (MOTI)
    term: Technology and Innovation, Mayor's Office of (MOTI)
  - id: ThriveNYC, Mayor's Office of
    term: ThriveNYC, Mayor's Office of
  - id: Transportation, Department of (DOT)
    term: Transportation, Department of (DOT)
  - id: Veterans' Services, Department of (DVS)
    term: Veterans' Services, Department of (DVS)
  - id: Water Board (NYWB)
    term: Water Board (NYWB)
  - id: Water Finance Authority, NYC Municipal (NYW)
    term: Water Finance Authority, NYC Municipal (NYW)
  - id: Waterfront Management Advisory Board (WMAB)
    term: Waterfront Management Advisory Board (WMAB)
  - id: Workforce Development, Mayor's Office of (WKDEV)
    term: Workforce Development, Mayor's Office of (WKDEV)
  - id: Workforce Investment Board (WIB)
    term: Workforce Investment Board (WIB)
  - id: Youth and Community Development, Department of (DYCD)
    term: Youth and Community Development, Department of (DYCD)