terms:
  - id: NYCOA
    term: Actuary, NYC Office of the
  - id: AJC
    term: Administrative Justice Coordinator, NYC Office of
  - id: OATH
    term: Administrative Trials and Hearings, Office of
  - id: DFTA
    term: Aging, Department for the
  - id: DOB
    term: Buildings, Department of
  - id: BIC
    term: Business Integrity Commission
  - id: CFB
    term: Campaign Finance Board
  - id: CIDI
    term: Center for Innovation through Data Intelligence
  - id: OCME
    term: Chief Medical Examiner, NYC Office of
  - id: ACS
    term: Children's Services, Administration for
  - id: NYCC
    term: City Council, New York
  - id: DCP
    term: City Planning, Department of
  - id: DCAS
    term: Citywide Administrative Services, Department of
  - id: CSC
    term: Civil Service Commission
  - id: CCRB
    term: Civilian Complaint Review Board
  - id: OCDV
    term: Combat Domestic Violence, Mayor's Office to
  - id: CGE
    term: Commission on Gender Equity
  - id: CCPC
    term: Commission to Combat Police Corruption
  - id: CAU
    term: Community Affairs Unit
  - id: COMP
    term: Comptroller
  - id: COIB
    term: Conflicts of Interest Board
  - id: DCA
    term: Consumer Affairs, Department of
  - id: MOCS
    term: Contract Services, Mayor's Office of
  - id: BOC
    term: Correction, Board of
  - id: DOC
    term: Correction, Department of
  - id: MOCJ
    term: Criminal Justice, Mayor's Office of
  - id: DCLA
    term: Cultural Affairs, Department of
  - id: MODA
    term: Data Analytics, Mayor's Office of
  - id: DDC
    term: Design and Construction, Department of
  - id: EDC
    term: Economic Development Corporation
  - id: Opportunity
    term: Economic Opportunity, Mayor's Office for
  - id: DOE
    term: Education, Department of
  - id: BOE
    term: Elections, Board of
  - id: OEM
    term: Emergency Management, Office of
  - id: OEC
    term: Environmental Coordination, Mayor's Office of
  - id: DEP
    term: Environmental Protection, Department of
  - id: OER
    term: Environmental Remediation, Mayor's Office of
  - id: EEPC
    term: Equal Employment Practices Commission
  - id: DOF
    term: Finance, Department of
  - id: FISA-OPA
    term: Financial Information Services Agency – Office of Payroll Administration
  - id: FDNY
    term: Fire Department, New York City
  - id: MOFP
    term: Food Policy Director, Mayor's Office of the
  - id: GNYC
    term: GreeNYC
  - id: HHC
    term: Health and Hospitals Corporation
  - id: DOHMH
    term: Health and Mental Hygiene, Department of
  - id: DHS
    term: Homeless Services, Department of
  - id: NYCHA
    term: Housing Authority, New York City
  - id: HPD
    term: Housing Preservation and Development, Department of
  - id: HRO
    term: Housing Recovery Operations
  - id: HRA
    term: Human Resources Administration
  - id: CCHR
    term: Human Rights, City Commission on
  - id: MOIA
    term: Immigrant Affairs, Mayor's Office of
  - id: IBO
    term: Independent Budget Office, NYC
  - id: MOIP
    term: Information Privacy, Mayor’s Office of
  - id: DOITT
    term: Information Technology and Telecommunications, Department of
  - id: OIG-NYPD
    term: Inspector General NYPD, Office of the
  - id: MOIGA
    term: Intergovernmental Affairs, Mayor's Office of
  - id: IA
    term: International Affairs, Mayor's Office for
  - id: DOI
    term: Investigation, Department of
  - id: OLR
    term: Labor Relations, NYC Office of
  - id: LPC
    term: Landmarks Preservation Commission
  - id: LAW
    term: Law Department
  - id: LOFT
    term: Loft Board
  - id: OLTPS
    term: Long-Term Planning &amp; Sustainability, Office of
  - id: OMB
    term: Management and Budget, Office of
  - id: FUND
    term: Mayor's Fund to Advance NYC
  - id: OM
    term: Mayor's Office
  - id: MOME
    term: Media and Entertainment, Mayor's Office of
  - id: MDSC
    term: Municipal Drug Strategy Council
  - id: NBAT
    term: New Business Acceleration Team
  - id: NYCGO
    term: NYC &amp; Company
  - id: NYCERS
    term: NYC Employees' Retirement System
  - id: SERVICE
    term: NYC Service
  - id: OPS
    term: Operations, Mayor's Office of
  - id: DPR
    term: Parks and Recreation, Department of
  - id: MOPD
    term: People with Disabilities, Mayor's Office of
  - id: NYPD
    term: Police Department
  - id: PPF
    term: Police Pension Fund
  - id: DOP
    term: Probation, Department of
  - id: PPB
    term: Procurement Policy Board
  - id: PUB-ADV
    term: Public Advocate
  - id: DesignCommission
    term: Public Design Commission
  - id: QuadAC
    term: Quadrennial Advisory Commission
  - id: DORIS
    term: Records and Information Services, Department of
  - id: ORR
    term: Recovery &amp; Resiliency, Mayor's Office of
  - id: RGB
    term: Rent Guidelines Board
  - id: DSNY
    term: Sanitation, Department of
  - id: SCA
    term: School Construction Authority
  - id: SBS
    term: Small Business Services, Department of
  - id: BSA
    term: Standards and Appeals, Board of
  - id: Sustainability
    term: Sustainability, Mayor's Office of
  - id: TAT
    term: Tax Appeals Tribunal, New York City
  - id: TC
    term: Tax Commission, New York City
  - id: TLC
    term: Taxi and Limousine Commission
  - id: MOTI
    term: Technology and Innovation, Mayor's Office of
  - id: DOT
    term: Transportation, Department of
  - id: DVS
    term: Veterans' Services, Department of
  - id: NYWB
    term: Water Board
  - id: NYW
    term: Water Finance Authority, NYC Municipal
  - id: WMAB
    term: Waterfront Management Advisory Board
  - id: WKDEV
    term: Workforce Development, Mayor's Office of
  - id: WIB
    term: Workforce Investment Board
  - id: DYCD
    term: Youth and Community Development, Department of