terms:
  - id: Bronx 1
    term: Bronx 1
  - id: bronx_2
    term:  Bronx 2
  - id: bronx_3
    term:  Bronx 3
  - id: bronx_4
    term:  Bronx 4
  - id: bronx_5
    term:  Bronx 5
  - id: bronx_6
    term:  Bronx 6
  - id: bronx_7
    term:  Bronx 7
  - id: bronx_8
    term:  Bronx 8
  - id: bronx_9
    term:  Bronx 9
  - id: bronx_10
    term:  Bronx 10
  - id: bronx_11
    term:  Bronx 11
  - id: bronx_12
    term:  Bronx 12
  - id: brooklyn_1
    term:  Brooklyn 1
  - id: brooklyn_2
    term:  Brooklyn 2
  - id: brooklyn_3
    term:  Brooklyn 3
  - id: brooklyn_4
    term:  Brooklyn 4
  - id: brooklyn_5
    term:  Brooklyn 5
  - id: brooklyn_6
    term:  Brooklyn 6
  - id: brooklyn_7
    term:  Brooklyn 7
  - id: brooklyn_8
    term:  Brooklyn 8
  - id: brooklyn_9
    term:  Brooklyn 9
  - id: brooklyn_10
    term:  Brooklyn 10
  - id: brooklyn_11
    term:  Brooklyn 11
  - id: brooklyn_12
    term:  Brooklyn 12
  - id: brooklyn_13
    term:  Brooklyn 13
  - id: brooklyn_14
    term:  Brooklyn 14
  - id: brooklyn_15
    term:  Brooklyn 15
  - id: brooklyn_16
    term:  Brooklyn 16
  - id: brooklyn_17
    term:  Brooklyn 17
  - id: brooklyn_18
    term:  Brooklyn 18
  - id: manhattan_1
    term:  Manhattan 1
  - id: manhattan_2
    term:  Manhattan 2
  - id: manhattan_3
    term:  Manhattan 3
  - id: manhattan_4
    term:  Manhattan 4
  - id: manhattan_5
    term:  Manhattan 5
  - id: manhattan_6
    term:  Manhattan 6
  - id: manhattan_7
    term:  Manhattan 7
  - id: manhattan_8
    term:  Manhattan 8
  - id: manhattan_9
    term:  Manhattan 9
  - id: manhattan_10
    term:  Manhattan 10
  - id: manhattan_11
    term:  Manhattan 11
  - id: manhattan_12
    term:  Manhattan 12
  - id: queens_1
    term:  Queens 1
  - id: queens_2
    term:  Queens 2
  - id: queens_3
    term:  Queens 3
  - id: queens_4
    term:  Queens 4
  - id: queens_5
    term:  Queens 5
  - id: queens_6
    term:  Queens 6
  - id: queens_7
    term:  Queens 7
  - id: queens_8
    term:  Queens 8
  - id: queens_9
    term:  Queens 9
  - id: queens_10
    term:  Queens 10
  - id: queens_11
    term:  Queens 11
  - id: queens_12
    term:  Queens 12
  - id: queens_13
    term:  Queens 13
  - id: queens_14
    term:  Queens 14
  - id: staten_island_1
    term:  Staten Island 1
  - id: staten_island_2
    term:  Staten Island 2
  - id: staten_island_3
    term:  Staten Island 3