terms:
  - id: Bronx 1
    term: Bronx 1
  - id: Bronx 2
    term:  Bronx 2
  - id: Brone 3
    term:  Bronx 3
  - id: Brone 4
    term:  Bronx 4
  - id: Brone 5
    term:  Bronx 5
  - id: Brone 6
    term:  Bronx 6
  - id: Brone 7
    term:  Bronx 7
  - id: Brone 8
    term:  Bronx 8
  - id: Brone 9
    term:  Bronx 9
  - id: Brone 10
    term:  Bronx 10
  - id: Brone 11
    term:  Bronx 11
  - id: Brone 12
    term:  Bronx 12
  - id: Brooklyn 1
    term:  Brooklyn 1
  - id: Brooklyn 2
    term:  Brooklyn 2
  - id: Brooklyn 3
    term:  Brooklyn 3
  - id: Brooklyn 4
    term:  Brooklyn 4
  - id: Brooklyn 5
    term:  Brooklyn 5
  - id: Brooklyn 6
    term:  Brooklyn 6
  - id: Brooklyn 7
    term:  Brooklyn 7
  - id: Brooklyn 8
    term:  Brooklyn 8
  - id: Brooklyn 9
    term:  Brooklyn 9
  - id: Brooklyn 10
    term:  Brooklyn 10
  - id: Brooklyn 11
    term:  Brooklyn 11
  - id: Brooklyn 12
    term:  Brooklyn 12
  - id: Brooklyn 13
    term:  Brooklyn 13
  - id: Brooklyn 14
    term:  Brooklyn 14
  - id: Brooklyn 15
    term:  Brooklyn 15
  - id: Brooklyn 16
    term:  Brooklyn 16
  - id: Brooklyn 17
    term:  Brooklyn 17
  - id: Brooklyn 18
    term:  Brooklyn 18
  - id: Manhattan 1
    term:  Manhattan 1
  - id: Manhattan 2
    term:  Manhattan 2
  - id: Manhattan 3
    term:  Manhattan 3
  - id: Manhattan 4
    term:  Manhattan 4
  - id: Manhattan 5
    term:  Manhattan 5
  - id: Manhattan 6
    term:  Manhattan 6
  - id: Manhattan 7
    term:  Manhattan 7
  - id: Manhattan 8
    term:  Manhattan 8
  - id: Manhattan 9
    term:  Manhattan 9
  - id: Manhattan 10
    term:  Manhattan 10
  - id: Manhattan 11
    term:  Manhattan 11
  - id: Manhattan 12
    term:  Manhattan 12
  - id: Queens 1
    term:  Queens 1
  - id: Queens 2
    term:  Queens 2
  - id: Queens 3
    term:  Queens 3
  - id: Queens 4
    term:  Queens 4
  - id: Queens 5
    term:  Queens 5
  - id: Queens 6
    term:  Queens 6
  - id: Queens 7
    term:  Queens 7
  - id: Queens 8
    term:  Queens 8
  - id: Queens 9
    term:  Queens 9
  - id: Queens 10
    term:  Queens 10
  - id: Queens 11
    term:  Queens 11
  - id: Queens 12
    term:  Queens 12
  - id: Queens 13
    term:  Queens 13
  - id: Queens 14
    term:  Queens 14
  - id: Staten Island 1
    term:  Staten Island 1
  - id: Staten Island 2
    term:  Staten Island 2
  - id: Staten Island 3
    term:  Staten Island 3