terms:
  - id: Accessibility
    term: Accessibility
  - id: Accounting
    term: Accounting
  - id: Advertising
    term: Advertising
  - id: Aged
    term: Aged
  - id: Alcohol
    term: Alcohol
  - id: Animal_welfare
    term: Animal Welfare
  - id: Archaeology
    term: Archaeology
  - id: Architecture
    term: Architecture
  - id: Art and Design
    term: Art and Design
  - id: Athletics
    term: Athletics
  - id: Banks And Banking
    term: Banks and Banking
  - id: Brooklyn
    term: Brooklyn
  - id: Bronx
    term: Bronx
  - id: Budget and Finance
    term: Budget and Finance
  - id: Building Code
    term: Building Code
  - id: Building Construction
    term: Building Construction
  - id: Buildings
    term: Buildings
  - id: Business
    term: Business
  - id: Celebrations and Parades
    term: Celebrations and Parades
  - id: Cemeteries
    term: Cemeteries
  - id: Census
    term: Census
  - id: Charities
    term: Charities
  - id: Children
    term: Children
  - id: City Planning
    term: City Planning
  - id: Civil Service
    term: Civil Service
  - id: Climate
    term: Climate
  - id: Coastal
    term: Coastal
  - id: Community Relations
    term: Community Relations
  - id: Consumers
    term: Consumers
  - id: Conventions
    term: Conventions
  - id: Correction
    term: Correction
  - id: Cost
    term: Cost
  - id: Courts
    term: Courts
  - id: Crime and Criminals
    term: Crime and Criminals
  - id: Criminal Justice
    term: Criminal Justice
  - id: Culture
    term: Culture
  - id: Data and Communications
    term: Data and Communications
  - id: Death
    term: Death
  - id: Demography and Population
    term: Demography and Population
  - id: Disability
    term: Disability
  - id: Discrimination
    term: Discrimination
  - id: Diseases
    term: Diseases
  - id: Drugs
    term: Drugs
  - id: Education
    term: Education
  - id: Elections and Voting
    term: Elections and Voting
  - id: Electric Power
    term: Electric Power
  - id: Emergencies
    term: Emergencies
  - id: Emergency Preparedness
    term: Emergency Preparedness
  - id: Employment
    term: Employment
  - id: Energy
    term: Energy
  - id: Engineering
    term: Engineering
  - id: Environment
    term: Environment
  - id: Equal Employment
    term: Equal Employment
  - id: Ethics
    term: Ethics
  - id: Ethnic groups
    term: Ethnic groups
  - id: Families
    term: Families
  - id: Finance
    term: Finance
  - id: Fire Fighting
    term: Fire Fighting
  - id: Firearms
    term: Firearms
  - id: Food
    term: Food
  - id: Food Supply
    term: Food Supply
  - id: Fuels
    term: Fuels
  - id: Gambling
    term: Gambling
  - id: Geography
    term: Geography
  - id: Government
    term: Government
  - id: Government - Citizen participation
    term: Government - Citizen participation
  - id: Hazard Mitigation
    term: Hazard Mitigation
  - id: Hazardous Materials
    term: Hazardous Materials
  - id: Health
    term: Health
  - id: History
    term: History
  - id: Homeless Persons
    term: Homeless Persons
  - id: Hospitals
    term: Hospitals
  - id: Hotels
    term: Hotels
  - id: Housing
    term: Housing
  - id: Housing - Limited Profit
    term: Housing - Limited Profit
  - id: Housing - Low Income
    term: Housing - Low Income
  - id: Human Rights
    term: Human Rights
  - id: Immigration
    term: Immigration
  - id: Industries
    term: Industries
  - id: Infrastructure
    term: Infrastructure
  - id: Insurance
    term: Insurance
  - id: Internet
    term: Internet
  - id: Islands
    term: Islands
  - id: Labor and Employment
    term: Labor and Employment
  - id: Land Use
    term: Land Use
  - id: Landmarks
    term: Landmarks
  - id: Languages
    term: Languages
  - id: Laws and legislation
    term: Laws and legislation
  - id: LGBTQ (Lesbian / Gay / Bisexual / Transgender / Queer or Questioning)
    term: LGBTQ (Lesbian / Gay / Bisexual / Transgender / Queer or Questioning)
  - id: Libraries
    term: Libraries
  - id: Licenses and Permits
    term: Licenses and Permits
  - id: Manhattan
    term: Manhattan
  - id: Maps
    term: Maps
  - id: Markets
    term: Markets
  - id: Mayor (Name)
    term: Mayor (Name)
  - id: Memorials
    term: Memorials
  - id: Mental Health
    term: Mental Health
  - id: Monuments
    term: Monuments
  - id: Motor Vehicles
    term: Motor Vehicles
  - id: Museums
    term: Museums
  - id: Neighborhoods
    term: Neighborhoods
  - id: Nutrition
    term: Nutrition
  - id: Officials and Employees
    term: Officials and Employees
  - id: Parking
    term: Parking
  - id: Parks and Recreation
    term: Parks and Recreation
  - id: Pensions
    term: Pensions
  - id: Pests
    term: Pests
  - id: Police
    term: Police
  - id: Police - Community Relations
    term: Police - Community Relations
  - id: Police - Discipline
    term: Police - Discipline
  - id: Politics and Government
    term: Politics and Government
  - id: Pollution
    term: Pollution
  - id: Poverty
    term: Poverty
  - id: Prices
    term: Prices
  - id: Purchasing Methods
    term: Purchasing Methods
  - id: Public Authorities
    term: Public Authorities
  - id: Public Health
    term: Public Health
  - id: Public Welfare
    term: Public Welfare
  - id: Queens
    term: Queens
  - id: Real Property
    term: Real Property
  - id: Records
    term: Records
  - id: Recreation
    term: Recreation
  - id: Recycling
    term: Recycling
  - id: Refuse and Refuse Disposal
    term: Refuse and Refuse Disposal
  - id: Religions
    term: Religions
  - id: Rent Control
    term: Rent Control
  - id: Rent Stabilization Law
    term: Rent Stabilization Law
  - id: Restaurants
    term: Restaurants
  - id: Retail
    term: Retail
  - id: Rivers
    term: Rivers
  - id: Sanitation
    term: Sanitation
  - id: Schools
    term: Schools
  - id: Schools - Administration
    term: Schools - Administration
  - id: Schools - Charter
    term: Schools - Charter
  - id: Schools - Parochial
    term: Schools - Parochial
  - id: Schools - Private
    term: Schools - Private
  - id: Schools - Buildings
    term: Schools - Buildings
  - id: Sewage
    term: Sewage
  - id: Small Business
    term: Small Business
  - id: Snow Removal
    term: Snow Removal
  - id: Special Districts
    term: Special Districts
  - id: State of New York
    term: State of New York
  - id: Staten Island
    term: Staten Island
  - id: Statistics
    term: Statistics
  - id: Street Vendors
    term: Street Vendors
  - id: Streets - Maintenance and Repair
    term: Streets - Maintenance and Repair
  - id: Streets and Highways
    term: Streets and Highways
  - id: Students
    term: Students
  - id: Subways
    term: Subways
  - id: Subways - Stations
    term: Subways - Stations
  - id: Supplies
    term: Supplies
  - id: Surveying
    term: Surveying
  - id: Taxation
    term: Taxation
  - id: Taxation - Exemption from
    term: Taxation - Exemption from
  - id: Taxation - Real Property
    term: Taxation - Real Property
  - id: Taxicabs
    term: Taxicabs
  - id: Teachers
    term: Teachers
  - id: Television
    term: Television
  - id: Terminals
    term: Terminals
  - id: Terrorism
    term: Terrorism
  - id: Toilets
    term: Toilets
  - id: Tolls
    term: Tolls
  - id: Tourists
    term: Tourists
  - id: Traffic and Parking
    term: Traffic and Parking
  - id: Traffic Safety
    term: Traffic Safety
  - id: Transit
    term: Transit
  - id: Transit - Rapid
    term: Transit - Rapid
  - id: Transportation
    term: Transportation
  - id: Transportation - Finance
    term: Transportation - Finance
  - id: Transportation - School
    term: Transportation - School
  - id: Transportation - Planning
    term: Transportation - Planning
  - id: Trees
    term: Trees
  - id: Trusts and Estates
    term: Trusts and Estates
  - id: Universities and Colleges
    term: Universities and Colleges
  - id: Vendors and Contracts
    term: Vendors and Contracts
  - id: Veterans
    term: Veterans
  - id: Volunteers
    term: Volunteers
  - id: Water
    term: Water
  - id: Water Supply
    term: Water Supply
  - id: Weapons
    term: Weapons
  - id: Weather
    term: Weather
  - id: Women
    term: Women
  - id: World Trade Center
    term: World Trade Center
  - id: Youth
    term: Youth