terms:
  - id: English
    term: English
  - id: Spanish
    term: Spanish
  - id: Chinese
    term: Chinese
  - id: Russian
    term: Russian
  - id: Arabic
    term: Arabic
  - id: Bengali
    term: Bengali
  - id: French
    term: French
  - id: Haitian Creole
    term: Haitian Creole
  - id: Italian
    term: Italian
  - id: Korean
    term: Korean
  - id: Polish
    term: Polish
  - id: Urdu
    term: Urdu
  - id: Yiddish
    term: Yiddish