terms:
  - id: District 1
    term: District 1
  - id: District 2
    term: District 2
  - id: District 3
    term: District 3
  - id: District 4
    term: District 4
  - id: District 5
    term: District 5
  - id: District 6
    term: District 6
  - id: District 7
    term: District 7
  - id: District 8
    term: District 8
  - id: District 9
    term: District 9
  - id: District 10
    term: District 10
  - id: District 11
    term: District 11
  - id: District 12
    term: District 12
  - id: District 13
    term: District 13
  - id: District 14
    term: District 14
  - id: District 15
    term: District 15
  - id: District 16
    term: District 16
  - id: District 17
    term: District 17
  - id: District 18
    term: District 18
  - id: District 19
    term: District 19
  - id: District 20
    term: District 20
  - id: District 21
    term: District 21
  - id: District 22
    term: District 22
  - id: District 23
    term: District 23
  - id: District 24
    term: District 24
  - id: District 25
    term: District 25
  - id: District 26
    term: District 26
  - id: District 27
    term: District 27
  - id: District 28
    term: District 28
  - id: District 29
    term: District 29
  - id: District 30
    term: District 30
  - id: District 31
    term: District 31
  - id: District 32
    term: District 32
  - id: District 75
    term: District 75
  - id: District 79
    term: District 79