terms:
  - id: district_1
    term: District 1
  - id: district_2
    term: District 2
  - id: district_3
    term: District 3
  - id: district_4
    term: District 4
  - id: district_5
    term: District 5
  - id: district_6
    term: District 6
  - id: district_7
    term: District 7
  - id: district_8
    term: District 8
  - id: district_9
    term: District 9
  - id: district_10
    term: District 10
  - id: district_11
    term: District 11
  - id: district_12
    term: District 12
  - id: district_13
    term: District 13
  - id: district_14
    term: District 14
  - id: district_15
    term: District 15
  - id: district_16
    term: District 16
  - id: district_17
    term: District 17
  - id: district_18
    term: District 18
  - id: district_19
    term: District 19
  - id: district_20
    term: District 20
  - id: district_21
    term: District 21
  - id: district_22
    term: District 22
  - id: district_23
    term: District 23
  - id: district_24
    term: District 24
  - id: district_25
    term: District 25
  - id: district_26
    term: District 26
  - id: district_27
    term: District 27
  - id: district_28
    term: District 28
  - id: district_29
    term: District 29
  - id: district_30
    term: District 30
  - id: district_31
    term: District 31
  - id: district_32
    term: District 32
  - id: district_75
    term: District 75
  - id: district_79
    term: District 79