terms:
  - id: accounting
    term: Accounting
  - id: advertising
    term: Advertising
  - id: aged
    term: Aged
  - id: alcohol
    term: Alcohol
  - id: animal_welfare
    term: Animal Welfare
  - id: archaeology
    term: Archaeology
  - id: architecture
    term: Architecture
  - id: art_and_design
    term: Art and Design
  - id: athletics
    term: Athletics
  - id: banks_and_banking
    term: Banks and Banking
  - id: brooklyn
    term: Brooklyn
  - id: bronx
    term: Bronx
  - id: budget_and_finance
    term: Budget and Finance
  - id: building_code
    term: Building Code
  - id: building_construction
    term: Building Construction
  - id: buildings
    term: Buildings
  - id: business
    term: Business
  - id: celebrations_and_parades
    term: Celebrations and Parades
  - id: cemeteries
    term: Cemeteries
  - id: census
    term: Census
  - id: charities
    term: Charities
  - id: children
    term: Children
  - id: city_planning
    term: City Planning
  - id: civil_service
    term: Civil Service
  - id: climate
    term: Climate
  - id: coastal
    term: Coastal
  - id: community_relations
    term: Community Relations
  - id: compliance
    term: Compliance
  - id: consumers
    term: Consumers
  - id: conventions
    term: Conventions
  - id: correction
    term: Correction
  - id: cost
    term: Cost
  - id: courts
    term: Courts
  - id: crime_and_criminals
    term: Crime and Criminals
  - id: criminal_justice
    term: Criminal Justice
  - id: culture
    term: Culture
  - id: data_and_communications
    term: Data and Communications
  - id: death
    term: Death
  - id: demography_and_population
    term: Demography and Population
  - id: disability
    term: Disability
  - id: discrimination
    term: Discrimination
  - id: diseases
    term: Diseases
  - id: drugs
    term: Drugs
  - id: education
    term: Education
  - id: elections_and_voting
    term: Elections and Voting
  - id: electric_power
    term: Electric Power
  - id: emergencies
    term: Emergencies
  - id: employment
    term: Employment
  - id: energy
    term: Energy
  - id: engineering
    term: Engineering
  - id: environment
    term: Environment
  - id: equal_employment
    term: Equal Employment
  - id: ethics
    term: Ethics
  - id: ethnic_groups
    term: Ethnic groups
  - id: families
    term: Families
  - id: finance
    term: Finance
  - id: fire_fighting
    term: Fire Fighting
  - id: firearms
    term: Firearms
  - id: food
    term: Food
  - id: food_supply
    term: Food supply
  - id: fuels
    term: Fuels
  - id: gambling
    term: Gambling
  - id: geography
    term: Geography
  - id: government
    term: Government
  - id: government_-_citizen_participation
    term: Government - Citizen participation
  - id: hazardous_materials
    term: Hazardous Materials
  - id: health
    term: Health
  - id: history
    term: History
  - id: homeless_persons
    term: Homeless Persons
  - id: hospitals
    term: Hospitals
  - id: hotels
    term: Hotels
  - id: housing
    term: Housing
  - id: housing_-_limited_profit
    term: Housing - Limited Profit
  - id: housing_-_low_income
    term: Housing - Low Income
  - id: human_rights
    term: Human Rights
  - id: immigration
    term: Immigration
  - id: industries
    term: Industries
  - id: infrastructure
    term: Infrastructure
  - id: insurance
    term: Insurance
  - id: internet
    term: Internet
  - id: islands
    term: Islands
  - id: labor_and_employment
    term: Labor and Employment
  - id: land_use
    term: Land Use
  - id: landmarks
    term: Landmarks
  - id: languages
    term: Languages
  - id: laws_and_legislation
    term: Laws and legislation
  - id: lgbtq_(lesbian_/_gay_/_bisexual_/_transgender_/_queer_or_questioning)
    term: LGBTQ (Lesbian / Gay / Bisexual / Transgender / Queer or Questioning)
  - id: libraries
    term: Libraries
  - id: licenses_and_permits
    term: Licenses and Permits
  - id: manhattan
    term: Manhattan
  - id: maps
    term: Maps
  - id: markets
    term: Markets
  - id: mayor_(name)
    term: Mayor (Name)
  - id: memorials
    term: Memorials
  - id: mental_health
    term: Mental Health
  - id: monuments
    term: Monuments
  - id: motor_vehicles
    term: Motor Vehicles
  - id: museums
    term: Museums
  - id: neighborhoods
    term: Neighborhoods
  - id: nutrition
    term: Nutrition
  - id: officials_and_employees
    term: Officials and Employees
  - id: parking
    term: Parking
  - id: parks_and_recreation
    term: Parks and Recreation
  - id: pensions
    term: Pensions
  - id: pests
    term: Pests
  - id: police
    term: Police
  - id: police_-_community_relations
    term: Police - Community Relations
  - id: police_-_discipline
    term: Police - Discipline
  - id: politics_and_government
    term: Politics and Government
  - id: pollution
    term: Pollution
  - id: poverty
    term: Poverty
  - id: prices
    term: Prices
  - id: purchasing_methods
    term: Purchasing Methods
  - id: public_authorities
    term: Public Authorities
  - id: public_welfare
    term: Public Welfare
  - id: queens
    term: Queens
  - id: real_property
    term: Real Property
  - id: records
    term: Records
  - id: recreation
    term: Recreation
  - id: recycling
    term: Recycling
  - id: refuse_and_refuse_disposal
    term: Refuse and Refuse Disposal
  - id: religions
    term: Religions
  - id: rent_control
    term: Rent Control
  - id: rent_stabilization_law
    term: Rent Stabilization Law
  - id: restaurants
    term: Restaurants
  - id: retail
    term: Retail
  - id: rivers
    term: Rivers
  - id: sanitation
    term: Sanitation
  - id: schools
    term: Schools
  - id: schools_-_administration
    term: Schools - Administration
  - id: schools_-_charter
    term: Schools - Charter
  - id: schools_-_parochial
    term: Schools - Parochial
  - id: schools_-_private
    term: Schools - Private
  - id: schools_-_buildings
    term: Schools - Buildings
  - id: sewage
    term: Sewage
  - id: small_business
    term: Small Business
  - id: snow_removal
    term: Snow Removal
  - id: special_districts
    term: Special Districts
  - id: state_of_new_york
    term: State of New York
  - id: staten_island
    term: Staten Island
  - id: statistics
    term: Statistics
  - id: street_vendors
    term: Street Vendors
  - id: streets_-_maintenance_and_repair
    term: Streets - Maintenance and Repair
  - id: streets_and_highways
    term: Streets and Highways
  - id: students
    term: Students
  - id: subways
    term: Subways
  - id: subways_-_stations
    term: Subways - Stations
  - id: supplies
    term: Supplies
  - id: surveying
    term: Surveying
  - id: taxation
    term: Taxation
  - id: taxation_-_exemption_from
    term: Taxation - Exemption from
  - id: taxation_-_real_property
    term: Taxation - Real Property
  - id: taxicabs
    term: Taxicabs
  - id: teachers
    term: Teachers
  - id: television
    term: Television
  - id: terminals
    term: Terminals
  - id: terrorism
    term: Terrorism
  - id: toilets
    term: Toilets
  - id: tolls
    term: Tolls
  - id: tourists
    term: Tourists
  - id: traffic_and_parking
    term: Traffic and Parking
  - id: traffic_safety
    term: Traffic Safety
  - id: transit
    term: Transit
  - id: transit_-_rapid
    term: Transit - Rapid
  - id: transportation
    term: Transportation
  - id: transportation_-_finance
    term: Transportation - Finance
  - id: transportation_-_school
    term: Transportation - School
  - id: transportation-_planning
    term: Transportation- Planning
  - id: trees
    term: Trees
  - id: trusts_and_estates
    term: Trusts and Estates
  - id: universities_and_colleges
    term: Universities and Colleges
  - id: vendors_and_contracts
    term: Vendors and Contracts
  - id: veterans
    term: Veterans
  - id: volunteers
    term: Volunteers
  - id: water
    term: Water
  - id: water_supply
    term: Water Supply
  - id: weapons
    term: Weapons
  - id: weather
    term: Weather
  - id: women
    term: Women
  - id: world_trade_center
    term: World Trade Center
  - id: youth
    term: Youth