terms:
  - id: Adjudications / Decisions
    term: Adjudications / Decisions
  - id: Audit Report
    term: Audit Report
  - id: Brochures
    term: Brochures
  - id: Budget / Finance
    term: Budget / Finance
  - id: Bulletins
    term: Bulletins
  - id: Calendars
    term: Calendars
  - id: Data / Statistics
    term: Data / Statistics
  - id: Delinquent Report Notice
    term: Delinquent Report Notice
  - id: Directives
    term: Directives
  - id: Environmental Impact Statements - Draft
    term: Environmental Impact Statements - Draft
  - id: Environmental Impact Statements - Final
    term: Environmental Impact Statements - Final
  - id: Executive Orders
    term: Executive Orders
  - id: Guides
    term: Guides
  - id: Laws / Legislation
    term: Laws / Legislation
  - id: Manuals / Directories
    term: Manuals / Directories
  - id: Minutes
    term: Minutes
  - id: Newsletters / Other Serial Publications
    term: Newsletters / Other Serial Publications
  - id: Other
    term: Other
  - id: Plans
    term: Plans
  - id: Press Releases
    term: Press Releases
  - id: Proceedings
    term: Proceedings
  - id: Reports - Annual
    term: Reports - Annual
  - id: Reports - Biannual (Twice a Year)
    term: Reports - Biannual (Twice a Year)
  - id: Reports - Biennial (Every Two Years)
    term: Reports - Biennial (Every Two Years)
  - id: Reports - Every 4 Years
    term: Reports - Every 4 Years
  - id: Reports - Every 5 Years
    term: Reports - Every 5 Years
  - id: Reports - Monthly
    term: Reports - Monthly
  - id: Reports - Weekly
    term: Reports - Weekly
  - id: Reports - Other (Consultant/Staff)
    term: Reports - Other (Consultant/Staff)
  - id: Studies
    term: Studies