development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_DEVELOPMENT_URL'] || "http://127.0.0.1:#{ENV['FCREPO_DEVELOPMENT_PORT']}/rest" %>
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_TEST_URL'] || "http://127.0.0.1:#{ENV['FCREPO_TEST_PORT']}/rest" %>
  base_path: /test
production:
  user: <%= ENV['FCREPO_DB_USER'] %>
  password: <%= ENV['FCREPO_DB_PASSWORD'] %>
  url: http://<%= ENV['FCREPO_HOST'] || 'localhost' %>:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || ENV['FCREPO_PORT'] || 8983 %>/<%= ENV['FCREPO_REST_PATH'] || 'rest' %>
  base_path: <%= ENV['FCREPO_BASE_PATH'] || '/prod' %>
